<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;


// https://laravel.com/docs/7.x/migrations#creating-indexes
use Illuminate\Support\Facades\Schema;
// Laravel uses the utf8mb4 character set by default, which includes support for storing "emojis" in the
// database. If you are running a version of MySQL older than the 5.7.7 release or MariaDB older than the 10.2.2 
// release, you may need to manually configure the default string length generated by migrations in order for 
// MySQL to create indexes for them. You may configure this by calling the Schema::defaultStringLength method 
// within your AppServiceProvider:

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array<class-string, class-string>
     */
    protected $policies = [
        // 'App\Models\Model' => 'App\Policies\ModelPolicy',
    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();
        Schema::defaultStringLength(191);
        //
    }
}
